// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rancho.Services.Identification.Shared.Data;

#nullable disable

namespace Rancho.Services.Identification.Shared.Data.Migrations
{
    [DbContext(typeof(IdentificationDbContext))]
    partial class IdentificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rancho.Services.Identification.Animals.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("EarTagNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ear_tag_number");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("original_version");

                    b.Property<Guid?>("RfidTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfid_tag_id");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("species");

                    b.HasKey("Id")
                        .HasName("pk_animals");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_animals_farm_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_animals_id");

                    b.ToTable("animals", "identification");
                });

            modelBuilder.Entity("Rancho.Services.Identification.Farms.Models.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("original_version");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_farms_id");

                    b.ToTable("farms", "identification");
                });

            modelBuilder.Entity("Rancho.Services.Identification.Tags.Models.RfidTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("FarmId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("original_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rfid_tags");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasDatabaseName("ix_rfid_tags_animal_id");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_rfid_tags_farm_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_rfid_tags_id");

                    b.ToTable("rfid_tags", "identification");
                });

            modelBuilder.Entity("Rancho.Services.Identification.Animals.Models.Animal", b =>
                {
                    b.HasOne("Rancho.Services.Identification.Farms.Models.Farm", "Farm")
                        .WithMany("Animals")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animals_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("Rancho.Services.Identification.Tags.Models.RfidTag", b =>
                {
                    b.HasOne("Rancho.Services.Identification.Animals.Models.Animal", "Animal")
                        .WithOne("RfidTag")
                        .HasForeignKey("Rancho.Services.Identification.Tags.Models.RfidTag", "AnimalId")
                        .HasConstraintName("fk_rfid_tags_animals_animal_id");

                    b.HasOne("Rancho.Services.Identification.Farms.Models.Farm", "Farm")
                        .WithMany("RfidTags")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rfid_tags_farms_farm_id");

                    b.Navigation("Animal");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("Rancho.Services.Identification.Animals.Models.Animal", b =>
                {
                    b.Navigation("RfidTag")
                        .IsRequired();
                });

            modelBuilder.Entity("Rancho.Services.Identification.Farms.Models.Farm", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("RfidTags");
                });
#pragma warning restore 612, 618
        }
    }
}
